### ISSUE TITLE
Stylowanie gis_osm_railways

### ISSUE THREAD

**Issue by OpenStreetMapPolska** [openstreetmap-polska/style-osm-standard#11]

**Comment by merkato** [comment]
Nie ma w tej warstwie informacji o mostach, tunelach, nie ma również informacji o klasie torów poza rozróżnieniem tramwajowe - kolejowe

**Comment by jendrusk** [comment]
Tak krawiec kraje jak mu materiału staje ;) Nie ma to nie będzie

**Comment by merkato** [comment]
Nie ma mostów, więc nie będzie skrzyżowań wielopoziomowych dróg, kolei, etc. Trzeba ustalić która warstwa wyżej - drogi czy koleje?

**Comment by jendrusk** [comment]
Raczej koleje... raz że siatka rzadsza a dwa że w terenie też drogi nie przykrywają torów ;)
Jesteś jeszcze w trakcie?
![image](https://user-images.githubusercontent.com/9802737/61933138-66b28f00-af85-11e9-8b67-8cce4724e270.png)

**Comment by merkato** [comment]
W tej skali koleje będą musiały być troszkę cieńsze...

**Comment by jendrusk** [comment]
Zakładam, że to już zakończone skoro zmergowane :)
