### ISSUE TITLE
Podobny projekt

### ISSUE THREAD

**Issue by lkzkk** [openstreetmap-polska/style-osm-standard#37]
Hej,

Czy przypadkiem https://github.com/charleyglynn/OSM-Shapefile-QGIS-stylesheets nie jest bardziej zaawansowany niz ten projekt? Wydaje sie troche osierocony, ale moze daloby sie go przejac i pracowac nad nim?

Ponadto: czy ten projekt ma jakas docelowa skale, czy mialby dzialac w calym zakresie skal jak mapnik?

**Comment by jendrusk** [comment]
Cześć Łukasz
Jest bardziej zaawansowany, bo skończony...  Plan jest taki żeby stworzyć większe repozytorium własnych styli i opublikować żeby były w jednym miejscu  - taki pomysł na współpracę OSM Polska i grupy użytkowników QGIS-a. Przy okazji miało to być ćwiczenie pozwalające twórcom OSM zapoznać się z QGIS, a użytkownikom QGIS-a z danymi OSM. Aktualnie dynamika trochę padła ale liczę że w zimie będzie więcej czasu to i prace bardziej ruszą. 
Jeśli masz ochotę pomóc to zapraszamy - do wewnętrznej komunikacji mamy czat na FB (tam wszyscy jesteśmy). Jeśli chcesz dołączyć do projektu, ale rozwijać swój własny styl też fajnie - założę Ci repo i dodam Cię do grupy.
W tym stylu założenie było takie, że wzorujemy się na OSM Carto, robimy dla pełnego zakersu skal, z czego trzymamy się progów określonych kafelkami
https://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by lkzkk** [comment]
Okej. Rozumiem trochę lepiej już chyba. Inicjatywa chwalebna, zobaczę czy uda mi się coś zrobić. Może to: https://github.com/openstreetmap-polska/style-osm-standard/issues/34
